version: '2'
services:
    food-app:
        image: food
        external_links:
            - food-mysql:mysql
            - food-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/food?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    food-mysql:
        extends:
            file: mysql.yml
            service: food-mysql
    food-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: food-elasticsearch
